__global__ void deform2D(cudaTextureObject_t, float*, float2*, float*, uint, uint);
__global__ void lsq(float*, float*, float*, int);
__global__ void reduce(float*, uint);
__global__ void gradient(cudaTextureObject_t, float*, float*, uint, uint);
__global__ void makeG(float*, float2*, float*, float*, uint, uint);
__global__ void makeMatrix(float*, float*);
__global__ void gdSum(float*, float*, float*, float*, float);
__global__ void myDot(float*, float*, float*);
__global__ void addVec(float*, float*);
__global__ void ewMul(float*,float*);
__global__ void resample(float*, float*, uint);
__global__ void scalMul(float*, float);
__global__ void vecCpy(float*, float*);
float residuals(float*, float*, uint);
void initCuda();
void genMip(cudaTextureObject_t, cudaArray*, uint, uint);
void cleanCuda();
void gradientDescent(float*, float*, float*, float*i, uint, uint);
