__global__ void deform2D(cudaTextureObject_t, float*, float2*, float*, uint, uint);
__global__ void deform2D_t(cudaTextureObject_t, float*, float2*, float*, uint, int2);
__global__ void deform2D_b(cudaTextureObject_t, float*, float2*, float*, uint, uint);
__global__ void lsq(float*, float*, float*, int);
__global__ void gradient(cudaTextureObject_t, float*, float*, uint, uint);
__global__ void makeG(float*, float2*, float*, float*, uint, uint);
__global__ void gdSum(float*, cudaTextureObject_t, float*, float*, uint, uint, int2);
__global__ void myDot(float*, float*, float*);
__global__ void addVec(float*, float*);
__global__ void ewMul(float*,float*);
__global__ void resample(float*, float*, uint);
__global__ void scalMul(float*, float);
__global__ void vecCpy(float*, float*);
float residuals(float*, float*, uint);
void initCuda();
void genMip(cudaTextureObject_t, cudaArray*, uint, uint);
void cleanCuda();
void gradientDescent(cudaTextureObject_t*, float*, float*, float*, uint, uint, int2);
void makeGArray(cudaArray*, float2*, float*, float*, uint, uint);
void makeHessian(float*, cudaTextureObject_t*);
